export enum Paths {
    Login = '/login',
    PasswordRecovery = '/password_recovery',
    Wizard = '/wizard',
    CamerasSearch = '/cameras_search',
    CamerasSettings = '/cameras_settings',
    Detectors = '/detectors',
    SetsEditor = '/sets_editor',
    Events = '/events',
    DiskFormat = '/disk_format',
    SMTP = '/smtp',
    EventManager = '/event_manager',
    UsersSimple = '/users_simple',
    System = '/system',
    Backup = '/backup',
    BasicVcSettings = '/basic_vc_settings',
    OldDefault = '/old_default',
    Diagnostics = '/diagnostics',
    CamerasReserve = '/cameras_reserve',
    UserSettings = '/user_settings',
    TV = '/tv',
    NotFound = '/*',
    StatusServers = "/statusServers",
    Plugins = "/plugins",
    InfoPlugins = '/info_plugins'
}
